### ISSUE TITLE
'pod install' doesn't work with the template

### ISSUE THREAD

**Issue by xhhuango** [lorentey/FrameworkTemplate#2]
This is an amazing project!!! However, I can't do 'pod install'
```
git clone https://github.com/lorentey/FrameworkTemplate.git
cd FrameworkTemplate
pod init
vi Podfile
// Add "pod 'BigInt', '~> 2.1'" into each target
pod install
```
It outputs:
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `BigInt (~> 2.1)` required by `Podfile`
- `BigInt (~> 2.1)` required by `Podfile`
- `BigInt (~> 2.1)` required by `Podfile`
- `BigInt (~> 2.1)` required by `Podfile`

Specs satisfying the `BigInt (~> 2.1)` dependency were found, but they required a higher minimum deployment target.
```

Would you please help me?!

**Comment by lorentey** [comment]
This isn't an issue with the FrameworkTemplate project, as it doesn't come with a Podfile.

Nevertheless, the error message seems pretty clear about the problem: 

```
Specs satisfying the `BigInt (~> 2.1)` dependency were found, but they required a higher minimum deployment target.
```

CocoaPod has ludicrously low deployment targets by default. You'll need to add `platform` specification(s) that match or exceed the requirements of BigInt:

https://guides.cocoapods.org/syntax/podfile.html#platform
